platform :ios, '8.0'
inhibit_all_warnings!
pod 'Parse', '~> 1.6'
pod 'SVProgressHUD', '~> 1.1'
pod 'UIActionSheet+Blocks', '~> 0.8'
pod 'Facebook-iOS-SDK', '~> 3.21'
pod 'UIAlertView+Blocks', '~> 0.8'
pod 'mailgun', '~> 1.0.3'
pod 'ParseFacebookUtils', '~> 1.6'


